services:
  telegram-bot:
    build: .
    container_name: semstore-bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  redis:
    image: redis:7-alpine
    container_name: semstore-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    env_file:
      - .env

volumes:
  redis_data: