name: Build and deploy to VPS

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set IMAGE_TAG (GIT SHA)
        id: set-tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USER }}/semstore-bot:${GITHUB_SHA} .
          docker push ${{ secrets.DOCKER_HUB_USER }}/semstore-bot:${GITHUB_SHA}

  deploy-to-vps:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (needed for docker-compose.prod.yml)
        uses: actions/checkout@v4

      - name: Upload docker-compose.prod.yml to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "/tmp/"
          overwrite: true
          debug: true

      - name: Move file into place and restart service on VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          envs: GITHUB_SHA,IMAGE_TAG
          script: |
            set -eux

            if ! sudo -n true 2>/dev/null; then
              echo "ERROR: user cannot run sudo without password. Aborting."
              exit 1
            fi

            sudo mv /tmp/docker-compose.prod.yml /semstore/sEmStote-bot-v2/docker-compose.yml
            sudo chown root:root /semstore/sEmStote-bot-v2/docker-compose.yml
            sudo chmod 644 /semstore/sEmStote-bot-v2/docker-compose.yml

            cd /semstore/sEmStote-bot-v2

            sudo sed -i "s|image: .*|image: ${{ secrets.DOCKER_HUB_USER }}/semstore-bot:${GITHUB_SHA}|g" docker-compose.yml

            docker-compose down || true
            docker-compose rm -f || true

            docker-compose up -d --no-deps --force-recreate telegram-bot

            docker image prune -f || true