name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USER }}/semstore-bot:latest .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin
          docker push ${{ secrets.DOCKER_HUB_USER }}/semstore-bot:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /semstore/sEmStote-bot-v2/
            docker pull ${{ secrets.DOCKER_HUB_USER }}/semstore-bot:latest
            docker-compose down
            docker-compose up -d